### PR TITLE
Fix draft being sorted at the bottom

### LINKED ISSUE #431: QUIK should sort drafts of newly created conversations at the top of the conversation list
Steps towards reproducibility:

1. Open QUIK.
2. Click on the + button.
3. Type in a new number.
4. Tap the avatar with the new number to create a new conversation.
5. Enter a message text.
6. Tap the back button.

My expectation: In the same way as for existing conversations, QUIK sorts the drafts at the top of the conversation list. And also shows them immediately.

QUIK currently displays these new drafts at the very end of the conversation list.
I only realised this today after a long time. Before, I just wondered why I had to scroll so far up after step 6.

QUIK 4.1.0 (F-Droid)

### LINKED ISSUE #513: :lady_beetle: [BUG] New conversation with draft is placed at the end of the conversations list
**Describe the bug**
When not sending a message in an existing conversation it is stored as draft and the conversation is placed at the top of the conversations list. This is very helpful not to forget it.
But when the draft is in a new conversation the conversation is placed at the very end of the conversations list. I first thought the message is lost when I eventually found it there.
**To Reproduce**
1. Choose new contact
2. write message and don't send
3. close conversation
4. Conversation is placed at the very end of the conversations list

**Expected behavior**
Conversation should be placed at the top of the list as it is done with existing conversations
**Smartphone (please complete the following information):**
 - Device: Shiftphone 6mq
 - OS: /e/OS Android 13
 - App Version 4.1.1]

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Inhishonor**
~~No idea, whether or not this actually fixes the issue, I am just guessing that a missing date was the problem.~~
Seems to have fixed it. Apparently, the date property wasn't getting passed to new conversation's drafts. (Maybe it was an Android 13 or e os thing)
Closes #513
Closes #431

### CODE REVIEW

**Comment by Inhishonor** [comment]
@octoshrimpy Needs to be merged after #508, as I had to use that change to get the database migration to work.

File: data/src/main/java/com/moez/QKSMS/migration/QkRealmMigration.kt [hunk 1]
```diff
@@ -253,6 +249,12 @@ class QkRealmMigration @Inject constructor(
             version++
         }
 
+        if (version == 12L) {
+            realm.schema.get("Conversation")
+                ?.addField("draftDate", Long::class.java, FieldAttribute.REQUIRED)
+            version++
+        }
+
```
Comment (4jNsY6fCVqZv) [inline data/src/main/java/com/moez/QKSMS/migration/QkRealmMigration.kt:257]: Does this change also improve things for devices that are still based on Android 11?
Because that's the case for me.
